### ISSUE TITLE
Compile Python to Executable

### ISSUE THREAD

**Issue by ppyht2** [JimWest/MeFaMo#11]
Hi Jim, thanks for creating this repo, this combined with `pylivelink ` opens a lot of a opportunities.

Can you share some details on how you created the stand along binary? Specifically how you've incorporate the libraries such as `mediapipe`  and `opencv`.

**Comment by JimWest** [comment]
Hi, oh yeah I missed it in the Readme. Here's the command which I used to create that exe.
You need to install pyinstaller and then use the included spec file:

```
pip install pyinstaller
pyinstaller --onefile .\examples\mefamo.spec
```

I will add it to the readme (and also add the spec file which includes the commands for including all libs etc).

**Comment by JimWest** [comment]
Added everything to git.
