### ISSUE TITLE
black screen with  obs virtual camera and other

### ISSUE THREAD

**Issue by greatAznur** [JimWest/MeFaMo#14]
i tested the first realease   on window and i have a black screen with  obs virtual camera and other

**Comment by JimWest** [comment]
Seems like an OpenCV Issue, so nothing really I could change, sorry.
You should look here if somebody finds a solution:

https://github.com/obsproject/obs-studio/issues/3635

**Comment by greatAznur** [comment]
I found another software its work with manycam

**Comment by greatAznur** [comment]
ok  i look for the link  thanks
