### ISSUE TITLE
Is this repository cross platform or windows only? 

### ISSUE THREAD

**Issue by grewalmanoj221** [JimWest/MeFaMo#15]
Hello
I am trying to use this repository on my Ubuntu system with UE 5 and I am not able to find source for PyLiveLink python library. I have tried many things but I am not able to connect with udp server with LiveLink.

I am new to UE 5, so I don't know if it's UE issue or any other issue.

Thank You. Cheers.

**Comment by JimWest** [comment]
I'm only developing on Windows, so can't really tell. But you can find the PyLiveLink here:
https://github.com/JimWest/PyLiveLinkFace

You can build it yourself and install it on your machine (like described in the Readme under the PyLiveLinkFace repo).
On my WSL Ubuntu 20.04 with Python 3.8 I can install PyLiveLink with pip, which Python version are you using?

**Comment by grewalmanoj221** [comment]
I was able to install PyLiveLink on Ubuntu with Python 3.8 and it was working fine. But the issue is with UE. UE5 was not detecting LiveLink app as a source also. I tried it on windows and it worked fine.
Thank You. Closing the issue.
