### ISSUE TITLE
eye movement / iris tracking

### ISSUE THREAD

**Issue by Qaanaaq** [JimWest/MeFaMo#16]
what would it take to enables the iris tracking? could it be enabled simply, or would it need some deeper implementation? 

2nd thing that would be very cool is some kind of recroding data straight from the app, to some .csv or something.

**Comment by JimWest** [comment]
I disabled Iris tracking cause it wasn't finished, but the Eye Points are there. Mediapipe will give you the Eye Points (but only in 2d, theyre not in the canonical 3d face model). So it will need some deeper implementation.

You could receive all data through an record it using my pylivelink python repo (https://github.com/JimWest/PyLiveLinkFace, which is also used here to send data), as it can send and receive it. But I have currently no plans to implement a recording feature, I will focus on tweaking this when I find more time.

**Comment by plcdnl** [comment]
How can i enable it also if only in 2d?
