### ISSUE TITLE
Very cool

### ISSUE THREAD

**Issue by delebash** [JimWest/MeFaMo#2]
I tried to use mediapipe with iClone.  My major problem with mediapipe is the jitter.  Even applying some filters I was still unable to get rid of the jitter enough to make it useful.  Did you find a way to filter out the jitter?

Here is my attempt with the hand mocap.  https://www.youtube.com/watch?v=j6JboJIlpfM

**Comment by JimWest** [comment]
Yeah mediapipe is pretty jittery, there were some Issues on the mediapipe github, like this one:
https://github.com/google/mediapipe/issues/825

But for my usecase, just using a list and use the mean for the blendshape for the last x values worked ok enough (the filter code is in my library to store and send the blendshapes): https://github.com/JimWest/PyLiveLinkFace/blob/7becb1d73fde740873820e75a26f7d606772a263/pylivelinkface/pylivelinkface.py#L196

**Comment by delebash** [comment]
Cool, I will take a look.
