### ISSUE TITLE
Is it a mistype error ?

### ISSUE THREAD

**Issue by Neill3d** [JimWest/MeFaMo#5]
In code of computing a stretch_max_right value, looks like there is a copy-paste mistype
stretch_max_right = -0.45 + \
            (0.45 * mouth_smile_right) + (0.36 * mouth_left)
Should it be mouth_right used here instead ?

https://github.com/JimWest/MeFaMo/blob/341813f8b33c57ef9eabdcb7c20c02c70963675b/mefamo/blendshapes/blendshape_calculator.py#L170

**Comment by JimWest** [comment]
Yes you're totally right, sorry for the late reply will fix and commit it.
