### ISSUE TITLE
#`self._live_link_face.set_blendshape(FaceBlendShape.MouthClose, mouth_open)`

### ISSUE THREAD

**Issue by xuyixun21** [JimWest/MeFaMo#9]
#`self._live_link_face.set_blendshape(FaceBlendShape.MouthClose, mouth_open)`    in blendshape_calculator.py
if I delete this code,the program will run well.Could you help me explain the meaning of this code

**Comment by JimWest** [comment]
You can delete every blendshape in the calculator and it still runs, but it's sending less blendshapes than to Unreal. A good explenation what the difference between MouthClose and JawOpen can be found in the Apple ARKit documentation: https://developer.apple.com/documentation/arkit/arblendshapelocationmouthclose?language=objc
